import { ArrowLeft, ChevronLeft, ChevronRight, Heart, MapPin, MoreHorizontal } from 'lucide-react';
import { useState } from 'react';
import type { Memory } from '../../types';

export function MemoryDetail({ memory, onBack, onFavorite, onEdit, onDelete }: { memory: Memory; onBack: () => void; onFavorite: () => void; onEdit: () => void; onDelete: () => void }) {
  const [image, setImage] = useState(0);
  const [menu, setMenu] = useState(false);
  const [confirm, setConfirm] = useState(false);
  const date = new Date(`${memory.date}T00:00:00`);
  return <div className="memory-detail"><header><button onClick={onBack} aria-label="목록으로"><ArrowLeft /></button><div className="detail-menu"><button onClick={() => setMenu(!menu)} aria-label="추억 메뉴"><MoreHorizontal /></button>{menu && <div><button onClick={onEdit}>수정</button><button className="danger" onClick={() => { setMenu(false); setConfirm(true); }}>삭제</button></div>}</div></header><div className="detail-heading"><span>{date.getFullYear()}년 {date.getMonth() + 1}월 {date.getDate()}일</span><h1>{memory.title}</h1></div><div className="detail-gallery"><img src={memory.images[image]} alt={memory.title} />{memory.images.length > 1 && <><button className="gallery-prev" onClick={() => setImage((image - 1 + memory.images.length) % memory.images.length)}><ChevronLeft /></button><button className="gallery-next" onClick={() => setImage((image + 1) % memory.images.length)}><ChevronRight /></button><span>{image + 1} / {memory.images.length}</span></>}</div>{memory.images.length > 1 && <div className="detail-thumbnails">{memory.images.map((item, index) => <button className={index === image ? 'active' : ''} onClick={() => setImage(index)} key={item}><img src={item} alt="" /></button>)}</div>}<div className="detail-content"><button className={memory.favorite ? 'detail-favorite active' : 'detail-favorite'} onClick={onFavorite}><Heart fill={memory.favorite ? 'currentColor' : 'none'} />{memory.favorite ? '즐겨찾기됨' : '즐겨찾기'}</button><p>{memory.description}</p>{memory.location && <div className="detail-location"><MapPin size={16} />{memory.location}</div>}<div className="detail-tags">{memory.tags?.map((tag) => <span key={tag}>#{tag}</span>)}</div></div>{confirm && <div className="confirm-backdrop"><div className="confirm-dialog"><h3>이 추억을 삭제할까요?</h3><p>삭제한 추억은 다시 되돌릴 수 없어요.</p><div><button onClick={() => setConfirm(false)}>취소</button><button className="danger" onClick={onDelete}>삭제</button></div></div></div>}</div>;
}
