import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import Root from './Root';
import { initializeNativeApp } from './lib/native';
import { initializeRoutePwa } from './pwa';
import './styles.css';
import './auth-onboarding.css';
import './nickname.css';
import './ai-test.css';
import './chat-typing.css';
import './chat-tools.css';
import './chat-extras.css';
import './notifications.css';
import './location.css';
import './home-simple.css';
import './home-dashboard.css';
import './home-couple-tools.css';
import './home-couple-layout.css';
import './memories-hub.css';
import './more.css';
import './more-services.css';
import './route-brand.css';
import './route-themes.css';
import './route-themes';
import './couple-connect.css';
import './home-map-overlay.css';
import './home-map-overlay';
import './close-standard.css';
import './mobile-apk-fixes.css';
import './mobile-polish-v3.css';
import './web-desktop.css';
import './native-back-ui';
import './app-icon-native';
import './profile-enhance';
import './couple-date-enhance';
import './settings-hub';
import './mobile-polish-v3';
import './more-enhance';

void initializeNativeApp();
initializeRoutePwa();

createRoot(document.getElementById('root')!).render(<StrictMode><Root /></StrictMode>);
